// 字段英文 key → 中文 label 映射
export const FIELD_LABELS: Record<string, string> = {
  applicant: '申请人',
  college: '学院',
  class_name: '班级',
  student_id: '学号',
  phone: '联系方式',
  advisor: '辅导员姓名',
  advisor_phone: '辅导员联系方式',
  parent_phone: '家长联系方式',
  reason: '事由',
  start_date: '开始时间',
  end_date: '结束时间',
  days: '天数',
  destination: '去向',
  transportation: '交通工具',
  return_time: '返校时间',
  leave_type: '请假类型',
  amount: '金额',
  invoice_no: '发票号码',
  date: '日期',
  category: '费用类别',
  payment_method: '收款方式',
  bank_account: '银行账号',
  bank_name: '开户行',
  notes: '备注',
  club_name: '社团名称',
  club_type: '社团类别',
  activity: '活动名称',
  purpose: '目的',
  venue: '地点/场地',
  participants: '人数',
  budget: '经费预算',
  description: '活动方案',
  start_time: '开始时间',
  end_time: '结束时间',
  department: '所属部门',
  estimated_cost: '预估费用',
  accommodation: '住宿安排',
  international: '是否出境',
  room_no: '教室编号',
  need_multimedia: '需多媒体设备',
}

export const getFieldLabel = (key: string): string => {
  return FIELD_LABELS[key] || key
}
